# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2fde141e0e4459894ecf51587f5312114422edcb522aa353e731475ad429efe3cf0811d08a8d5c991047dd249c586d3a53d12aa25978cf57f92b3182543e90a

test:
  secret_key_base: 980a10b4ba2ab89c8b1993c8374f84714b8d27047caa9b16689f1c619606814476f861855acbe46dbbecb44c03da6af760eddbb16288b86d9e7108ff096d7d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
